### ISSUE TITLE
vscode下运行dev:h5 一直卡在编译阶段。

### ISSUE THREAD

**Issue by AdamvvYau** [DimplesY/uniapp-unocss-starter#1]
vscode下运行dev:h5 一直卡在编译阶段，yarn build:h5可以正常编译，但yarn dev:h5则一直卡在Compiling...  请问有遇到这种情况吗？请帮忙看看。谢谢！

PS D:\Workspace\src\uniapp-unocss> yarn dev:h5
yarn run v1.22.19
$ uni
Please note that in running mode, due to log output, sourcemap, and uncompressed source code, the performance and package size are not as good as release mode.
Compiling...

**Comment by DimplesY** [comment]
> vite 默认的端口是5173，uniapp官方在编译h5端的时候没有提供打印，你访问5173能显示出页面吗

**Comment by DimplesY** [comment]
> vscode下运行dev:h5 一直卡在编译阶段，yarn build:h5可以正常编译，但yarn dev:h5则一直卡在Compiling... 请问有遇到这种情况吗？请帮忙看看。谢谢！
> 
> PS D:\Workspace\src\uniapp-unocss> yarn dev:h5 yarn run v1.22.19 $ uni Please note that in running mode, due to log output, sourcemap, and uncompressed source code, the performance and package size are not as good as release mode. Compiling...

项目使用的依赖进行了更新，目前使用更新到 vite4 没有发现问题，你可以换个包管理器尝试一下

**Comment by AdamvvYau** [comment]
谢谢！
